[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfoamd"
version = "0.0.10"
description = "Pythonic manipulation of OpenFOAM dictionaries and case files."
authors = [{name = "Marc Goldbach", email = "mgoldbach@myyahoo.com"}]
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["openfoam", "cfd", "simulation", "python"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "pint",
    "rich",
    "ipython",
]

[project.urls]
Home = "https://github.com/mcgoldba/pyFoamd"

[project.scripts]
pf = "pyfoamd.__main__:main"

[tool.setuptools.packages.find]
include = ["pyfoamd*"]

[tool.setuptools.package-data]
pyfoamd = ["config.ini"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true
